services:
  cache:
    env_file: '.env'
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
